spring:
  application:
    name: de-la-do-para-backend

logging:
  structured:
    format:
      console: logstash

management:
  endpoints:
    web:
      exposure:
        include: health
      discovery:
        enabled: false
  endpoint:
    health:
      show-details: never
      show-components: never
      probes:
        enabled: true
